name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
    - uses: actions/checkout@v2
    - name: cache vendor
      id: cache
      uses: actions/cache@v1
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: composer install
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install -n --prefer-dist
    - name: copy .env
      run: cp .env-github-actions .env
    - name: generate key
      run: php artisan key:generate
    - name: migrate
      run: php artisan migrate
    - name: unit test
      run: ./vendor/bin/phpunit

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
      - name: remove .env if exists
        run: |
          rm -f .env
      - name: ssh key generate
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ID_RSA }}
        run: |
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
      - name: make ssh_config
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          touch ~/.ssh/config
          echo -n -e "Host reserview\nHostName reserview.net\nUser rsync\nPort $SSH_PORT\nIdentityFile /home/runner/.ssh/id_rsa\nStrictHostKeyChecking no\nUserKnownHostsFile ~/.ssh/known_hosts" > ~/.ssh/config
      - name: add known hosts
        run: 
          ssh-keyscan reserview.net >> ~/.ssh/known_hosts
      - name: add permisstion
        run: |
          chmod 0700 ~/.ssh
          chmod 700 home/runner
      - name: rsync deploy
        run: rsync -rptgDvz --delete  ./ reserview:/var/www/html/my-laravel
      - name: migrate database
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: ssh -i -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no rsync@reserview.net 'cd /var/www/html/my-laravel && php artisan migrate'